name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
env:
  FORESIGHT_UPLOADER_SIGNER_URL: https://upload.thundra.me


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Test
      run: go test  ./... -coverprofile=./cov/coverage.out
    - name: Thundra Registry
      if: success() || failure()
      run: |
        ls -lR
        npm config set registry ${{ secrets.THUNDRA_REGISTRY }}
        npm config set _auth ${{ secrets.THUNDRA_REGISTRY_AUTH }}
    - name: Foresight Action
      if: success() || failure()
      uses: thundra-io/foresight-test-kit-action@initial-action
      with:
        api_key: ${{ secrets.THUNDRA_APIKEY }}
        coverage_format: golang
        coverage_path: |
          **/cov/**
        cli_version: 213.3.12

