name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
env:
  FORESIGHT_UPLOADER_SIGNER_URL: https://upload.service.runforesight.me
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Test
      run: |
        mkdir cov
        mkdir test
        go clean -testcache 
        go test -v > test/out.txt ./... -coverprofile=cov/coverage.out
        cat test/out.txt

