name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Test
      run: |
        mkdir cov
        go test -v > out.txt ./... -coverprofile=cov/coverage.out
        ls -lR
    - name: Thundra Registry
      if: success() || failure()
      run: |
        ls -lR
        npm config set registry ${{ secrets.THUNDRA_REGISTRY }}
        npm config set _auth ${{ secrets.THUNDRA_REGISTRY_AUTH }}
    - name: Foresight Action
      if: success() || failure()
      uses: runforesight/foresight-test-kit-action@build-runforesight
      with:
        api_key: ${{ secrets.THUNDRA_APIKEY }}
        test_framework: golang
        test_format: txt
        test_path: out.txt
        coverage_format: golang
        coverage_path: |
          **/cov/**
        cli_version: 123.321.1

